### ISSUE TITLE
Add `preserve` option

### ISSUE THREAD

**Issue by MoOx** [reworkcss/rework-custom-media#2]
Like it has been done for rework-vars, it would be nice to have a `preserve` option that helps to debug & act like a fallback:

Considering the following snippet

``` css
@custom-media --screen (screen);
@media --screen {
  html { background: red; }
}
```

We got

``` css
@media screen {
  html { background: red; }
}
```

With preserve we can output

``` css
@custom-media --screen (screen);
@media screen, --screen {
  html { background: red; }
}
```

(This last example is totally working on Chrome, Safari & Firefox http://jsbin.com/zuhovi/1/edit - with --screen before, Safari fails to parse the `@media`)

What do you think about that guys ?
